pipeline {
  agent any

  options { timestamps() }


  parameters {
    string(name: 'AWS_REGION', defaultValue: 'ap-south-1', description: 'AWS region')
    string(name: 'S3_BUCKET', defaultValue: 'sameer-ml-artifacts-ap-south-1', description: 'S3 artifacts bucket')
    string(name: 'S3_PREFIX', defaultValue: 'ml/textcls', description: 'S3 base prefix')
    string(name: 'MODEL_VERSION', defaultValue: 'v1.0.0', description: 'Artifact version')
    string(name: 'ECR_REPO', defaultValue: 'textcls-infer', description: 'ECR repo name')

  }

  environment {
    AWS_DEFAULT_REGION = "${params.AWS_REGION}"
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Download artifacts from S3') {
      steps {
            withCredentials([usernamePassword(
            credentialsId: 'aws-jenkins-basic',
            usernameVariable: 'AWS_ACCESS_KEY_ID',
            passwordVariable: 'AWS_SECRET_ACCESS_KEY'
            )]) {
            sh """
                mkdir -p artifacts/versioned/${params.MODEL_VERSION}
                aws s3 cp s3://${params.S3_BUCKET}/${params.S3_PREFIX}/versioned/${params.MODEL_VERSION}/saved_model.tar.gz \
                artifacts/versioned/${params.MODEL_VERSION}/saved_model.tar.gz
            """
        }

      }
    }

    stage('Docker build (TF Serving)') {
      steps {
        sh """
          docker build -t textcls-tfserving:${params.MODEL_VERSION} \
            --build-arg MODEL_VERSION=${params.MODEL_VERSION} \
            -f inference/Dockerfile .
        """
      }
    }
  }
}


stage('Push image to ECR') {
  steps {
    withCredentials([usernamePassword(
      credentialsId: 'aws-jenkins-basic',
      usernameVariable: 'AWS_ACCESS_KEY_ID',
      passwordVariable: 'AWS_SECRET_ACCESS_KEY'
    )]) {
      sh """
        set -e

        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        REGISTRY=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
        IMAGE_LOCAL=textcls-tfserving:${MODEL_VERSION}
        IMAGE_REMOTE=${REGISTRY}/${ECR_REPO}:${MODEL_VERSION}

        # Ensure repo exists (idempotent)
        aws ecr describe-repositories --repository-names ${ECR_REPO} >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name ${ECR_REPO} >/dev/null

        # Login, tag, push
        aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REGISTRY}
        docker tag ${IMAGE_LOCAL} ${IMAGE_REMOTE}
        docker push ${IMAGE_REMOTE}

        echo "PUSHED_IMAGE=${IMAGE_REMOTE}"
      """
    }
  }
}
