pipeline {
  agent any

  options { timestamps() }


  parameters {
    string(name: 'AWS_REGION', defaultValue: 'ap-south-1', description: 'AWS region')
    string(name: 'S3_BUCKET', defaultValue: 'sameer-ml-artifacts-ap-south-1', description: 'S3 artifacts bucket')
    string(name: 'S3_PREFIX', defaultValue: 'ml/textcls', description: 'S3 base prefix')
    string(name: 'MODEL_VERSION', defaultValue: 'v1.0.0', description: 'Artifact version')
    string(name: 'ECR_REPO', defaultValue: 'textcls-infer', description: 'ECR repo name')
    string(name: 'ENDPOINT_NAME', defaultValue: 'textcls-endpoint-dev', description: 'SageMaker endpoint name')
    string(name: 'INSTANCE_TYPE', defaultValue: 'ml.m5.large', description: 'SageMaker instance type')
    string(name: 'INITIAL_INSTANCE_COUNT', defaultValue: '1', description: 'Initial instances')
    string(name: 'SAGEMAKER_EXEC_ROLE_ARN', defaultValue: 'arn:aws:iam::570617927874:role/sagemaker-textcls-exec-role', description: 'SageMaker execution role ARN')


  }

  environment {
    AWS_DEFAULT_REGION = "${params.AWS_REGION}"
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Download artifacts from S3') {
      steps {
            withCredentials([usernamePassword(
            credentialsId: 'aws-jenkins-basic',
            usernameVariable: 'AWS_ACCESS_KEY_ID',
            passwordVariable: 'AWS_SECRET_ACCESS_KEY'
            )]) {
            sh """
                mkdir -p artifacts/versioned/${params.MODEL_VERSION}
                aws s3 cp s3://${params.S3_BUCKET}/${params.S3_PREFIX}/versioned/${params.MODEL_VERSION}/saved_model.tar.gz \
                artifacts/versioned/${params.MODEL_VERSION}/saved_model.tar.gz
            """
        }

      }
    }

    stage('Docker build (TF Serving)') {
      steps {
        sh """
          docker build -t textcls-tfserving:${params.MODEL_VERSION} \
            --build-arg MODEL_VERSION=${params.MODEL_VERSION} \
            -f inference/Dockerfile .
        """
      }
    }

    stage('Push image to ECR') {
        steps {
            withCredentials([usernamePassword(
            credentialsId: 'aws-jenkins-basic',
            usernameVariable: 'AWS_ACCESS_KEY_ID',
            passwordVariable: 'AWS_SECRET_ACCESS_KEY'
            )]) {
            sh '''
            set -e

            ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
            REGISTRY=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
            IMAGE_LOCAL=textcls-tfserving:${MODEL_VERSION}
            IMAGE_REMOTE=${REGISTRY}/${ECR_REPO}:${MODEL_VERSION}

            aws ecr describe-repositories --repository-names ${ECR_REPO} >/dev/null 2>&1 || \
                aws ecr create-repository --repository-name ${ECR_REPO} >/dev/null

            aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REGISTRY}
            docker tag ${IMAGE_LOCAL} ${IMAGE_REMOTE}
            docker push ${IMAGE_REMOTE}

            echo "PUSHED_IMAGE=${IMAGE_REMOTE}"
            '''

            }
        }
        }


    stage('Deploy to SageMaker') {
        steps {
            withCredentials([usernamePassword(
            credentialsId: 'aws-jenkins-basic',
            usernameVariable: 'AWS_ACCESS_KEY_ID',
            passwordVariable: 'AWS_SECRET_ACCESS_KEY'
            )]) {
            sh '''
                set -e

                ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
                REGISTRY=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
                ECR_IMAGE=${REGISTRY}/${ECR_REPO}:${MODEL_VERSION}

                MODEL_DATA_S3=s3://${S3_BUCKET}/${S3_PREFIX}/versioned/${MODEL_VERSION}/saved_model.tar.gz


                python3 -m venv .venv
                . .venv/bin/activate
                pip install --upgrade pip
                pip install -r sagemaker/requirements.txt


                python sagemaker/deploy_endpoint.py \
                --region ${AWS_DEFAULT_REGION} \
                --endpoint ${ENDPOINT_NAME} \
                --exec-role-arn "${SAGEMAKER_EXEC_ROLE_ARN}" \
                --instance-type ${INSTANCE_TYPE} \
                --initial-count ${INITIAL_INSTANCE_COUNT} \
                --ecr-image ${ECR_IMAGE} \
                --model-data-s3 ${MODEL_DATA_S3}

            '''
            }
        }
        }


  }
}



